package dev.atvremote.app

/**
 * Icons for Apple's built-in tvOS apps.
 *
 * None of these are in any App Store — a lookup for `com.apple.TVSettings` and
 * its neighbours comes back empty in every region and entity — and the handful
 * that do have iOS listings return a square icon that sits awkwardly in a 5:3
 * tile. So the drawer draws its own: original artwork in one visual language,
 * generated by `tools/generate_app_icons.py`, sized to the tile exactly as the
 * tvOS artwork of third-party apps is.
 *
 * Original rather than Apple's own, which this project has no licence to
 * redistribute. They read as the app they stand for without being a copy of it.
 */
fun appleIcon(bundleId: String): Int? {
    if (!bundleId.startsWith("com.apple.", ignoreCase = true)) return null

    val id = bundleId.lowercase()
    return when {
        "watchlist" in id || "videos" in id || id == "com.apple.tv" -> R.drawable.ic_app_tv
        "sing" in id -> R.drawable.ic_app_sing
        "music" in id -> R.drawable.ic_app_music
        "podcast" in id -> R.drawable.ic_app_podcasts
        "appstore" in id || "store" in id -> R.drawable.ic_app_appstore
        "settings" in id || "preferences" in id -> R.drawable.ic_app_settings
        "photo" in id || "slideshow" in id -> R.drawable.ic_app_photos
        "search" in id || "spotlight" in id -> R.drawable.ic_app_search
        "homesharing" in id || "computer" in id -> R.drawable.ic_app_computers
        "arcade" in id || "game" in id -> R.drawable.ic_app_arcade
        "fitness" in id || "workout" in id -> R.drawable.ic_app_fitness
        "facetime" in id -> R.drawable.ic_app_facetime
        // Anything else of Apple's still beats a pair of initials.
        else -> R.drawable.ic_app_generic
    }
}

/**
 * The bundle id to fetch artwork under, or null when nothing should be asked.
 *
 * Apple's apps are answered locally by [appleIcon], so they never reach the
 * network: their tvOS ids are in no catalogue, and their iOS ids return artwork
 * in the wrong shape and a different visual language from the rest of the row.
 */
fun storeBundleId(bundleId: String): String? =
    if (bundleId.startsWith("com.apple.", ignoreCase = true)) null else bundleId
